<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="EL2819" Id="{f53f1521-ea95-4522-96ee-49d4e6c1f88a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL2819
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
*
*
*)]]></ST>
    </Implementation>
    <LineIds Name="EL2819">
      <LineId Id="9" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>