<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="FB_Axis" Id="{4b9e9ace-3043-48df-9fdf-571ce181897a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Axis
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR_IN_OUT
	stAxisStruct						: AxisStruct;
END_VAR
VAR
	fbCommStateMachine			: FB_Communication;
	fbDriveVirtual				: FB_DriveVirtual_V2;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbCommStateMachine(stAxisStruct:= stAxisStruct);
fbDriveVirtual(stAxisStruct:= stAxisStruct);]]></ST>
    </Implementation>
    <LineIds Name="FB_Axis">
      <LineId Id="34" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="90" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>