<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="EL1908_v0_00" Id="{315cdc73-9713-4451-8fa1-31757d7b5399}" SpecialFunc="None">
    <Declaration><![CDATA[///EL1908 | 8-channel digital input terminal, TwinSAFE, 24 V DC
FUNCTION_BLOCK EL1908_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EL1908_v0_00">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>