<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="EL2904_v0_00" Id="{8eea216c-65d1-4ea0-8eb8-d3ee8a85c501}" SpecialFunc="None">
    <Declaration><![CDATA[///EL2904 | 4-channel digital output terminal, TwinSAFE, 24 V DC, 0.5 A
FUNCTION_BLOCK EL2904_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EL2904_v0_00">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>