<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="EL6900_v0_00" Id="{f88fd9c8-623c-4763-990b-4dbc24d5502f}" SpecialFunc="None">
    <Declaration><![CDATA[///EL6900 | TwinSAFE PLC
FUNCTION_BLOCK EL6900_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EL6900_v0_00">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>