<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="EL7201" Id="{41c27df6-567d-42f4-a342-26c06a4b0130}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL7201
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EL7201">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>