<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="EL1512_v0_00" Id="{6a19c24c-7a4f-4101-8287-18a7e0ef6f56}" SpecialFunc="None">
    <Declaration><![CDATA[///EL1512 | 2-channel, up/down counter, 24 V DC, 1 kHz, 16 bit
FUNCTION_BLOCK EL1512_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EL1512_v0_00">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>