<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="EL3214" Id="{0ef824af-3384-4b63-9d1f-7d6cf6b0bd23}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL3214
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
*
*
*)]]></ST>
    </Implementation>
    <LineIds Name="EL3214">
      <LineId Id="9" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>