<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="EK1200" Id="{98544b5d-cfdf-476a-90c0-230bdaff0ec8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EK1200
VAR_INPUT
	En: BOOL;
END_VAR
VAR_OUTPUT
	EnO: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[EnO:=En;
]]></ST>
    </Implementation>
    <LineIds Name="EK1200">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>